version: '3'

services:
  shellshock:
    build: ./shellshock/
    ports:
      - "3002:22"
    restart: always
  sudo_lpe:
    build: ./sudo_lpe/
    ports:
      - "3001:22"
    restart: always
  npm-programatic:
    build: ./npm-programatic/
    ports:
      - "3003:3003"
    restart: always
  lodas:
    build: ./lodas/
    ports:
      - "3004:3004"
    restart: always
  uppy_backend:
    build: ./uppy/backend
    ports:
      - "3005:3005"
    restart: always
  uppy_frontend:
    build: ./uppy/frontend
    ports:
      - "3006:3006"
    restart: always
  heartbleed:
    build: ./heartbleed/
    ports:
      - "3007:443"
    restart: always
